---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bazzite-dx
# description will be included in the image's metadata
description: Development focused image based on Bazzite with proprietary Nvidia drivers.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: script
    snippets:
      - "mkdir /nix" # Workaround to allow installing nix with composefs
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
      # - source: my-image/usr   # copies `files/my-image/usr/*` to `/usr/` inside the image
      #   destination: /usr
  - type: justfiles
    validate: true
  - type: dnf
    repos:
      copr:
        # - atim/starshipo
    install:
      packages:
        - virt-manager
        - edk2-ovmf
        - qemu
        - gpu-screen-recorder-ui
        - code
        - git-lfs
        - golang
        - dotnet-sdk-9.0
        - dotnet-runtime-9.0
        # - ghostty
    # remove:
    #   packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        # - firefox
        # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  # - type: default-flatpaks
  #   configurations:
  #     - scope: user
  #       repo:
  #         # you can override the title to make inclusion of both system and user repos clearer
  #         title: Flathub (user)
  #     - notify: true
  #       scope: system
  #       repo:
  #         title: Flathub (system)
  #       install: # system flatpaks we want all users to have and not remove
  #         - org.mozilla.firefox

  - type: signing # this sets up the proper policy & signing files for signed images to work fully